name: Android UI Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ui_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Cache Gradle Wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Build and Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Emulator and System Image
        run: |
          sdkmanager --install "system-images;android-30;google_apis;x86_64" "emulator"
          avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" -d pixel

      - name: Start Emulator
        run: |
          nohup emulator -avd test -no-snapshot -no-window -gpu swiftshader_indirect > /dev/null 2>&1 &
          adb wait-for-device
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0

      - name: Run Instrumented Tests
        run: ./gradlew connectedCheck

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-test-reports
          path: app/build/outputs/androidTest/connected/
          retention-days: 7
