name: Android UI Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ui_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # Tăng timeout nếu cần thiết

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Cache Gradle Wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Build and Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Set up Android Emulator
        uses: android-actions/setup-android@v3

      - name: Start Android Emulator and Run Instrumented Tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel
          script: ./gradlew connectedCheck


      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-test-reports
          path: app/build/outputs/androidTest/connected/*
          retention-days: 7